# Generated by Django 5.0.9 on 2026-05-16 19:07

import apps.crypto.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_var_name', models.CharField(max_length=255)),
                ('encrypted_value', apps.crypto.fields.EncryptedTextField(blank=True, default='')),
                ('injection_pattern', models.TextField(default='this.{target_var_name} = R04oo.d0x116_("{value}");')),
                ('validated', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='projects.projectpair')),
                ('source_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='variables.variable')),
                ('target_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_mappings', to='variables.sourcefile')),
            ],
            options={
                'ordering': ['target_var_name'],
            },
        ),
    ]
