# Generated by Django 5.0.9 on 2026-05-16 19:01

import apps.crypto.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('obf_name', models.CharField(blank=True, default='', max_length=255)),
                ('path', models.CharField(max_length=1024)),
                ('is_default', models.BooleanField(default=False)),
                ('validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='variables.folder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='projects.project')),
            ],
            options={
                'ordering': ['path'],
                'unique_together': {('project', 'path')},
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('obf_name', models.CharField(blank=True, default='', max_length=255)),
                ('relative_path', models.CharField(max_length=1024)),
                ('language', models.CharField(choices=[('java', 'Java'), ('other', 'Other')], default='java', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='variables.folder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
            ],
            options={
                'ordering': ['relative_path'],
                'unique_together': {('project', 'relative_path')},
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('obf_name', models.CharField(blank=True, default='', max_length=255)),
                ('var_type', models.CharField(default='String', max_length=100)),
                ('raw_value', models.TextField(blank=True, default='')),
                ('evaluated_value', apps.crypto.fields.EncryptedTextField(blank=True, default='')),
                ('is_sensitive', models.BooleanField(default=True)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('validated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('line_start', models.IntegerField(blank=True, null=True)),
                ('line_end', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='variables.sourcefile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
