# Generated by Django 5.0.9 on 2026-05-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='mode',
            field=models.CharField(choices=[('apply', 'Apply'), ('generate', 'Generate'), ('audit', 'Audit'), ('obfuscate', 'Obfuscate')], default='apply', max_length=20),
        ),
    ]
