# Generated by Django 5.0.9 on 2026-05-16 18:57

import apps.crypto.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('root_path', models.CharField(max_length=1024)),
                ('language', models.CharField(choices=[('java', 'Java')], default='java', max_length=50)),
                ('project_type', models.CharField(choices=[('monolith', 'Monolith'), ('microservice', 'Microservice')], default='monolith', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('encryption_key', apps.crypto.fields.EncryptedTextField()),
                ('algorithm', models.CharField(choices=[('xor_base64', 'XOR + Base64')], default='xor_base64', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_source', to='projects.project')),
                ('target_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairs_as_target', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
