"""Tests for the master-key in-memory context."""
import pytest

from apps.crypto.services.master_key import (
    set_master_password,
    get_fernet,
    get_salt,
    clear_master_password,
)


@pytest.fixture(autouse=True)
def _clear():
    clear_master_password()
    yield
    clear_master_password()


def test_get_before_set_raises():
    with pytest.raises(RuntimeError):
        get_fernet()


def test_set_and_use():
    set_master_password("master-1")
    f = get_fernet()
    token = f.encrypt(b"hello")
    assert f.decrypt(token) == b"hello"


def test_rotation_changes_keys():
    set_master_password("a")
    salt_a = get_salt()
    set_master_password("b")
    salt_b = get_salt()
    # New salt generated by default on each set_password
    assert salt_a != salt_b


def test_clear_returns_to_uninitialized():
    set_master_password("x")
    clear_master_password()
    with pytest.raises(RuntimeError):
        get_fernet()
