server.port=8086
spring.datasource.url=jdbc:h2:file:./Converter;AUTO_SERVER=TRUE;
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always
#spring.jap.defer-datasource-initialisation=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=800MB
spring.servlet.multipart.max-request-size=800MB
upload.directory=C:/Users/AC2I/Documents/test_projects/java_test/converter/upload
app.directory=C:/Users/AC2I/Documents/test_projects/java_test/converter
# Lancer avec : java -Xmx700m -XX:MaxMetaspaceSize=256m -jar converter-0.0.1-SNAPSHOT.jar
# Nombre maximum de conversions XSLT simultanees (a adapter par client)
app.max-concurrent-conversions=2
# logging.level.root=OFF
# spring.main.banner-mode=off

# Activation HTTPS
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=ac2i123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=converterAC2I


# Forcer HTTPS
server.ssl.protocol=TLS

# Session
server.servlet.session.timeout=15m
